In [1]:
import pandas as pd
import sqlite3
import os

In [2]:
root_dir = os.environ.get("PROJECT_DIR")

In [3]:
root_dir

'C:\\Users\\25471\\Desktop\\Python 3.12\\song-recommender\\song-recommender'

In [4]:
def get_connection():
    conn=sqlite3.connect(f"{root_dir}/database/song_recommendations_db.db")
    conn.row_factory = sqlite3.Row
    return conn

In [5]:
def all_songs():
    conn=get_connection()
    cursor=conn.cursor()
    cursor.execute("SELECT * FROM songs")
    songs= []

    song_objects = cursor.fetchall()
    conn.close()

    for s in song_objects:
        songs.append(dict(s))

    return songs

In [6]:
data = all_songs()

In [7]:
len(data)

114000

In [8]:
songs_df = pd.DataFrame(data)

In [9]:
songs_df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,FALSE,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,FALSE,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,FALSE,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,FALSE,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,FALSE,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [10]:
num_feat= songs_df.select_dtypes(include='number').columns.to_list()

In [11]:
x = songs_df[num_feat]

In [12]:
x.head()

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,73,230666,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4
1,55,149610,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4
2,57,210826,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4
3,71,201933,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3
4,82,198853,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test = train_test_split(x, test_size =0.2, random_state =42)

In [21]:
from sklearn.neighbors import NearestNeighbors

In [22]:
model = NearestNeighbors(n_neighbors = 10, metric='cosine', algorithm='brute') #Building the model

In [23]:
model.fit(x_train)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=10)

In [29]:
x_test.sample()

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
37587,48,415660,0.553,0.732,7,-5.206,0,0.262,0.622,0.0,0.163,0.436,152.59,4

In [31]:
distances, indices = model.kneighbors([[37587, 48,	415660,	0.553,	0.732,	7	-5.206,	0,	0.262,	0.622,	0.0,	0.163,	0.436,	152.59,	4]])

C:\Users\25471\Desktop\Python 3.12\song-recommender\song-recommender\.env\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [32]:
indices

array([[56683, 39560, 62914, 14265, 82679, 77599, 20528, 69844, 51405,
        73368]])

In [34]:
songs_df.iloc[indices[0]] #Recommended songs

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
56683,5411TEB6tlzvuF5A4oyldr,Mitski,Bury Me At Makeout Creek,Francis Forever,78,149680,FALSE,0.535,0.448,2,-9.167,1,0.0279,0.00262,0.000019,0.1150,0.3200,101.986,4,indie-pop
39560,1grvqYbhgqJxwdzeY1vgSb,Scorpions,Blackout,No One Like You (2015 - Remaster),31,238866,FALSE,0.441,0.796,9,-2.851,0,0.0431,0.01670,0.000003,0.1660,0.6960,118.146,4,german
62914,4eBgSyDDQqKHyxCvkqghs7,STEREO DIVE FOUNDATION,STORYSEEKER,STORYSEEKER,47,232800,FALSE,0.573,0.769,2,-7.784,1,0.0736,0.03160,0.000000,0.1870,0.5560,111.980,4,j-pop
14265,7cc31Uz5vC9ErZqd4dz8KR,Pinkfong,Pinkfong & Baby Shark Halloween Zombi,Tiburones Zombi de Halloween,20,114541,FALSE,0.639,0.498,2,-8.206,0,0.0529,0.85700,0.000000,0.0697,0.5730,98.031,4,children
82679,6rWjSJfzdvmsgdFBtJUXGo,The Dukes Of Stratosphear,Chips From The Chocolate Fireball,Collideascope - 2001 Mix,21,202960,FALSE,0.552,0.744,11,-4.126,0,0.0295,0.00483,0.000847,0.1690,0.8000,91.582,4,power-pop
77599,3yfRDsK74hvMIBLR1VX3nO,Sandra De Sá,Sandra Sá,Retratos e Canções,46,234333,FALSE,0.611,0.400,9,-12.371,1,0.0230,0.16800,0.000000,0.1190,0.5470,81.050,4,pagode
20528,4753v8gP7AT9df2zgxa2N9,Burna Boy;Wizkid,New Grooves,B. D’OR,0,189800,FALSE,0.873,0.658,4,-8.031,0,0.1080,0.00858,0.006100,0.0999,0.4830,104.033,4,dance
69844,00cCBPlCmZfnOM49RKOl88,Sujatha;Sriram Parthasarathy;Saijanani,Nala Dhamayanthi,Thirumaangalya Dharunam,21,285093,FALSE,0.786,0.705,0,-10.754,1,0.0585,0.09380,0.000066,0.0767,0.4570,96.989,4,malay
51405,7tavmiMMEibizGOiXoozar,AP Dhillon;Gurinder Gill;Money Musik,Not by Chance,Goat,63,159130,FALSE,0.725,0.821,6,-5.147,1,0.1540,0.10300,0.000003,0.1180,0.1350,91.821,4,hip-hop
73368,15OrzHa6hLqiGpb8DTPjAz,Argy,The Interior Journey,Power Of Detachment,32,325500,FALSE,0.686,0.858,0,-8.528,1,0.0430,0.04450,0.709000,0.1020,0.0728,123.982,4,minimal-techno